# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dea4a429cd44d9a9519dae2c69026d779ac5961c2033089d65760677d19d2d12b8b17b7f152d4a2fe5ef89c946e14223fa4dc0cb0c7d89ba579735034ae10d8

test:
  secret_key_base: aa171ffd35e398918eb3b70a2aa2d5b0a327fdf592e427378e05f69e5682e7b920a42eba1ce781729f7db7390b91599c608b1107be3a7c9e471d4cb41d32fb4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
